### ISSUE TITLE
Unraid template

### ISSUE THREAD

**Issue by ados8** [successible/cleanslate#10]
For those using Unraid will there be an official template for the community store.
Unraid can use docker compose but it's nowhere near as polished as templates from the community store.
Looking forward to trying this project, it looks well designed!

**Comment by paulzakin** [comment]
Nope - not at this time. I’d never even heard of it until you mentioned it! Open to a pull request though, if you or someone else with the expertise wants to take a crack at? I will reopen this issue if that is the case. Thanks!
