### ISSUE TITLE
Scrolling while adding recipe/workout/food abandons work in progress without warning

### ISSUE THREAD

**Issue by Wgelyjr** [successible/cleanslate#104]
Firefox mobile, selfhosted instance. Sometimes when scrolling the window will "grab" as if I were at the top of the page overscrolling to refresh, and perform a refresh, removing any work I'd done on the recipe/food/workout data entry.

Let me know if there's any more data I can provide!

**Comment by paulzakin** [comment]
I think device type, OS, browser and a GIF it happening, if possible!

**Comment by Wgelyjr** [comment]
![Screenshot_20240426-182646.png](https://github.com/successible/cleanslate/assets/39679453/175c3f1f-9c37-4b2f-af01-1b93feb84d77)

https://github.com/successible/cleanslate/assets/39679453/9f79df88-b0ca-44fb-bea7-eda62c84cd62

**Comment by Wgelyjr** [comment]
Pixel 7, that's important 

![Screenshot_20240426-182916.png](https://github.com/successible/cleanslate/assets/39679453/6219dbe2-6185-4d1a-8a0f-a31bfef0c386)

**Comment by paulzakin** [comment]
Hmmmmm - can you try chrome?

**Comment by Wgelyjr** [comment]
Does not seem to occur with Chrome 124.0.6367.82

**Comment by paulzakin** [comment]
OK! I would just use Chrome for now if the error bothers you. I’ll try to fix it eventually.

**Comment by Wgelyjr** [comment]
I'm too rabid for FOSS to use Chrome, but that's on me - I can live with the bug. Sounds good, thanks for looking!
