### ISSUE TITLE
Bug when adding weight to recipe and adding it to daily

### ISSUE THREAD

**Issue by sgomez-cornelis** [successible/cleanslate#105]
![image](https://github.com/successible/cleanslate/assets/94002308/bbe7d17b-45c2-4c68-88dc-1010ca99738a)

Found a bug when setting the weight for a recipe in the serving weight part. After that food is added and set in grams, the calorie counter resets to the value of that item and disregards all other items from the list.

**Comment by sgomez-cornelis** [comment]
To reproduce the bug:
1) Add any random items to the list (from the known or already indexed list).
2) Create a recipe with a few ingredients.
3) Set the portion weight for the recipe.
4) Add the new custom recipe to the list with a weight set in grams.

**Comment by paulzakin** [comment]
one, good find! 

Two, can you do a GIF instead - my brain for whatever reason is not handling text well

**Comment by sgomez-cornelis** [comment]
![Bug](https://github.com/successible/cleanslate/assets/94002308/ec7e6695-e9d1-4f1f-9808-c8e24c7d1dbb)

**Comment by paulzakin** [comment]
Should be fixed, let me know if it worked for you!
