### ISSUE TITLE
Display objective measurement alongside subjective measurement

### ISSUE THREAD

**Issue by Wgelyjr** [successible/cleanslate#106]
e.g., when selecting "one slice" of bread, provide a way to see how many g/ml/oz/tbsp/floz one slice is equivalent to

Feels like it could be a pain but I figured it was worth pitching.

**Comment by paulzakin** [comment]
Could be an interesting idea! I’m worried that it would clutter the interface though. I would need a sketch or mock up of what you have in mind

**Comment by paulzakin** [comment]
Closing. Will reopen with a response!

**Comment by Wgelyjr** [comment]
![Screenshot_20240513-135618.png](https://github.com/successible/cleanslate/assets/39679453/f27962af-e8e1-4e85-996b-1e1c5e6e07c0)

Here's my disgusting mockup! I figure there's plenty of room on this screen. Perhaps all available measurements could be beneath the buttons? In my mind I imagine this would update as text is entered.

**Comment by Wgelyjr** [comment]
I think this would also help the app be a tiny bit more proactive. Being able to see the calorie/protein estimate before submitting a record reduces friction.

**Comment by paulzakin** [comment]
Oh, this is nice! I like this idea - I'll take a look at it this weekend.

**Comment by paulzakin** [comment]
Ok, finally addressed this. It was a very good idea that I took way to long to get too. If you have any comments, let me know!

Resolved in #162
