### ISSUE TITLE
Selfhostable version without firebase?

### ISSUE THREAD

**Issue by Hense** [successible/cleanslate#112]
Hello!

I think this is a pretty cool project and would like to self host it myself.
But the reason why I self host is to avoid Google and Microsoft, etc. (And also why I am having a hard time selecting any of the apps for calorie tracking, they all require an account, which I am not interested in)
So the dependency on Firebase is an issue to me. 
Is that possible to exclude/remove somehow?
I don't need users at all tbh, I am the only one who is going to use the app, and everything I host are only available locally (I can VPN from my phone when I am out and about 😄 )

**Comment by paulzakin** [comment]
It’s a reasonable request, but the app itself is built around Firebase. So a fair amount of work may be involved. Let me think about it and scope out how much work it may take. I’ll post on this thread with my updates!

**Comment by paulzakin** [comment]
Ok, I reviewed it and the tentative answer is yes - it will take some time to do it but I think it is feasible without too much work. Maybe in two weeks?

**Comment by Hense** [comment]
This is your project, so you set the timelines ;)
And if it is not possible, then that is all good and if I am the only one who has requested this, it might also not be worth your time :)

But I appreciate the answers, so fingers crossed 🤞

**Comment by paulzakin** [comment]
Yup, I appreciate that - honestly it's been on mind for a while, simply because the people that would self-host and the people that would want to use Firebase are rarely the same lol

**Comment by paulzakin** [comment]
I finished the beta implementation a couple days ago. This weekend when I have more time, I’ll wrap it up and post instructions.

**Comment by Hense** [comment]
Damn, that was quick 😮👍 
Well, I will be looking forward to trying it out 😄

**Comment by paulzakin** [comment]
Almost done - I'll post on this thread in a couple of hours for you to give it a shot!

**Comment by paulzakin** [comment]
Ok, those instructions in the README.md should be pretty clear - give me a shot and let me know how it goes

**Comment by Hense** [comment]
Should I continue to write here or open a new issue if I experience any issues?

**Comment by paulzakin** [comment]
Let’s say open a new issue
