### ISSUE TITLE
Unable to create user when not using Firebase

### ISSUE THREAD

**Issue by Hense** [successible/cleanslate#117]
Reading this part "Go to the domain of your newly deployed web service (Step #3). Log in with your HASURA_GRAPHQL_ADMIN_SECRET defined in .env. Click Data, then public, then profiles, then Insert Row. On this screen, enter no input. Instead, click Save. This will create a new Profile. Click to Browse Rows. Take note of the authId of the row you just made. That is your (very long) credential to log in."

I have navigated to http://127.0.0.1:8120/console/data/default/schema/public but my public folder is empty, and from what i understand from the above it should have a schema called "profiles".

I am running the docker image (I called the image "clean-slate" when building) with the following arguments:
 docker run -p 8120:8080 -e HASURA_DOMAIN=localhost:8080 -e HASURA_GRAPHQL_ADMIN_SECRET={adminsecret] -e HASURA_GRAPHQL_DATABASE_URL=postgres://clean-slate:{password}@{ip}:{port}/clean-slate -e HASURA_GRAPHQL_ENABLE_CONSOLE=true clean-slate

I get these errors when running the docker image
```
{"level":"error","msg":"connecting to graphql-engine server failed","time":"2023-05-28T14:58:17Z"}
{"level":"info","msg":"possible reasons:","time":"2023-05-28T14:58:17Z"}
{"level":"info","msg":"1) Provided root endpoint of graphql-engine server is wrong. Verify endpoint key in config.yaml or/and value of --endpoint flag","time":"2023-05-28T14:58:17Z"}
{"level":"info","msg":"2) Endpoint should NOT be your GraphQL API, ie endpoint is NOT https://hasura-cloud-app.io/v1/graphql it should be: https://hasura-cloud-app.io","time":"2023-05-28T14:58:17Z"}
{"level":"info","msg":"3) Server might be unhealthy and is not running/accepting API requests","time":"2023-05-28T14:58:17Z"}
{"level":"info","msg":"4) Admin secret is not correct/set","time":"2023-05-28T14:58:17Z"}
{"level":"info","msg":"","time":"2023-05-28T14:58:17Z"}
time="2023-05-28T14:58:17Z" level=fatal msg="making http request failed: Get \"https://localhost:8080/v1/version\": dial tcp 127.0.0.1:8080: connect: connection refused"

    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at Object.<anonymous> (/cleanslate/migrate.js:16:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(1499) [Uint8Array] [
      123,  34, 108, 101, 118, 101, 108,  34,  58,  34, 105, 110,
      102, 111,  34,  44,  34, 109, 115, 103,  34,  58,  34,  72,
      101, 108, 112,  32, 117, 115,  32, 105, 109, 112, 114, 111,
      118, 101,  32,  72,  97, 115, 117, 114,  97,  33,  32,  84,
      104, 101,  32,  99, 108, 105,  32,  99, 111, 108, 108, 101,
       99, 116, 115,  32,  97, 110, 111, 110, 121, 109, 105, 122,
      101, 100,  32, 117, 115,  97, 103, 101,  32, 115, 116,  97,
      116, 115,  32, 119, 104, 105,  99, 104,  92, 110,  97, 108,
      108, 111, 119,  32,
      ... 1399 more items
    ]
  ],
  pid: 13,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(1499) [Uint8Array] [
    123,  34, 108, 101, 118, 101, 108,  34,  58,  34, 105, 110,
    102, 111,  34,  44,  34, 109, 115, 103,  34,  58,  34,  72,
    101, 108, 112,  32, 117, 115,  32, 105, 109, 112, 114, 111,
    118, 101,  32,  72,  97, 115, 117, 114,  97,  33,  32,  84,
    104, 101,  32,  99, 108, 105,  32,  99, 111, 108, 108, 101,
     99, 116, 115,  32,  97, 110, 111, 110, 121, 109, 105, 122,
    101, 100,  32, 117, 115,  97, 103, 101,  32, 115, 116,  97,
    116, 115,  32, 119, 104, 105,  99, 104,  92, 110,  97, 108,
    108, 111, 119,  32,
    ... 1399 more items
  ]
}

Node.js v18.16.0
```

I tried building an image where i reversed the the order of the commands in the entrypoint.sh. That removed the above errors, but I am still not getting anything in my public folder

**Comment by paulzakin** [comment]
Yup, the Hasura migrations are tricky - let me run this locally and see if I can come up with a mitigation

**Comment by paulzakin** [comment]
Ok, can replicate, pushing fix now

**Comment by paulzakin** [comment]
Ok, fixed - give the README.md another read - it should get you unstuck!

**Comment by Hense** [comment]
Works :D

Although I am running docker run with "-p 8120:8080" still.

A new problem have arisen though

When I try to press "save" under Insert Row, i get the following error:
Insert failed!
Not-NULL violation. null value in column "authId" of relation "profiles" violates not-null constraint

**Comment by paulzakin** [comment]
Progress - Ah, I know why - give me a sec - fix incoming - that code that fixed that was on a branch I nuked when trying this all out lol

**Comment by Hense** [comment]
Well, at least you are not starting from scratch 😋

**Comment by paulzakin** [comment]
Very true! Ok merged - give it another try - rebuild the image and run the container and then go to the admin panel

**Comment by Hense** [comment]
So far so good. I got an AuthId now.
But when I try to login on the website, i get this error in the console: "Uncaught (in promise) ReferenceError: CryptoKey is not defined"
at n (webcrypto.js:2:25)
    at get_sign_verify_key.js:6:9
    at O (get_sign_verify_key.js:16:54)
    at R.sign (sign.js:65:33)
    at D.sign (sign.js:11:1)
    at U.sign (sign.js:19:1)
    at j (getJWT.ts:35:8)
    at onClick (TokenLoginButtons.tsx:39:31)
    at Object.eU (react-dom.production.min.js:54:315)
    at eH (react-dom.production.min.js:54:468)

**Comment by paulzakin** [comment]
Are you using HTTPS for the client?

**Comment by Hense** [comment]
That did it. Took some more time as my reverse proxy config messed up my Hasura connection. But I have also fixed that now.

Now it logs "x-hasura-admin-secret/x-hasura-access-key required, but not found", it is not an error in the console.
But at the same time it shows a modal "No profile matches that token!"

My HASURA_GRAPHQL_ADMIN_SECRET env variable is set, and i can't find anywhere else in the README where i need to set it

**Comment by paulzakin** [comment]
What credential are you using to login on the client? The authId of your profile or the admin key?

**Comment by Hense** [comment]
I use the GUID from the AuthId column, gotten through the Hasura console. I have pasted it into NotePad to avoid funky formatting. So i don't know/think i can do anymore to ensure that it is the correct Id

I have also tried to paste in the HASURA ADMIN SECRET, which gives the same log.

The log is occuring in my Chrome Dev tools console

Yes, I am able to :)

If I should hazard a guess it seems like a header is not send correctly.

**Comment by paulzakin** [comment]
OK, I actually know what it is

**Comment by paulzakin** [comment]
Committed to fix - pull down and rebuild the container and let me know what you get

**Comment by Hense** [comment]
I am in, leeeeet's goooo! :D

Awesome, it seems to be working as intended. I will close this issue and open a new one if anything comes up.
Thank you very much for the dedicated effort :)

**Comment by paulzakin** [comment]
For additional security, you can also have nginx serve the HTTP security headers in src/public/_headers. However, that is optional. 

Added that section to the README.md - we run those headers on our production instance, but you may want to add them on your own
