### ISSUE TITLE
Looping Loading Animation

### ISSUE THREAD

**Issue by endlessblink** [successible/cleanslate#125]
Hi, when I try to enter the site through the desktop (on Brave browser), the loading animation keeps looping.
How can I solve this?

Thanks!
Noam

**Comment by paulzakin** [comment]
Hey! 

So I'm not seeing anything in my error logs and I tried out Brave on my computer and it worked - but let us try a couple of things.

One, totally clear your cache and try again - https://support.brave.com/hc/en-us/articles/360048833872-How-Do-I-Clear-Cookies-And-Site-Data-In-Brave-

If that does not work, can you right click and inspect when on the app - click the console tab, and take a screenshot of what the output is?

**Comment by paulzakin** [comment]
Closing this until further update :)
