### ISSUE TITLE
Last update broke the page 

### ISSUE THREAD

**Issue by sgomez92** [successible/cleanslate#126]
For some reason the last update completely broke the page on both chrome and brave browsers on my phone. It all looks zoomed out and I can see tags on some UI elements.

**Comment by sgomez92** [comment]
This is how it looks on my mobile device (Samsung Galaxy S23 Ultra)
![SmartSelect_20230609_134614_Chrome.jpg](https://github.com/successible/cleanslate/assets/131557313/f8854e8b-9128-4d3b-805b-51a123546050)

![SmartSelect_20230609_134629_Chrome.jpg](https://github.com/successible/cleanslate/assets/131557313/10aa8136-9644-4789-b66f-d9e3a43750c7)

**Comment by paulzakin** [comment]
Yup, just fixed it - thanks for the super fast heads up! Click anywhere on the page and it will be fixed
