### ISSUE TITLE
Using docker-compose for a portainer instance of clean slate

### ISSUE THREAD

**Issue by logand99** [successible/cleanslate#134]
I really want to self host clean slate. I use portainer to manage all my docker apps. I cannot for the life of me get this deployed in portainer. I have spent the past 5 hours working on this with no luck. Just curious if someone would be willing to help?

**Comment by paulzakin** [comment]
I’d be happy to help you this weekend when I free up! In the meantime, can you provide some more context or detail on your set up? I’ve only ever helped people set up via docker are not portainer - so it will be a new learning experience for me.

**Comment by logand99** [comment]
portainer is just a tool to make managing docker containers easier. Typically when setting up something in portainer, you just paste in a docker-compose file and maybe a .env file if needed. Then portainer automatically pulls all the images and deploys all the containers needed for that app. I tried several different ways and was not successful.

**Comment by paulzakin** [comment]
Makes sense - I’ll give it a spin this weekend

**Comment by paulzakin** [comment]
First question. Clean slate is really three things a front end, which is just a folder of HTML files. A server and a database which of these three are you trying to run via portainer?

**Comment by logand99** [comment]
Ideally all of them. How do the html files get served? I assumed the front end would be a web server running nginx or apache or something to serve the front end, and then that would talk to all the background services.

**Comment by paulzakin** [comment]
Depends on your setup - most people who self-host do it via `nginx` but I've only ever focused on getting the back two working together - the server + database. The self-hoster would provide their own certificate as well. Let me see if I can set up a Docker Compose setup that orchestrates stuff together

**Comment by paulzakin** [comment]
Ok, so I finished: so, good news and bad news.

- Bad news: Portainer is not viable. It does not support Docker [Build Args](https://github.com/portainer/portainer/issues/3042) which Clean Slate needs to operate. Sorry if that is a deal breaker for you!

- Good news: Via docker compose, self-deployment is far easier! If you look at the `README.md` now, you just need a server with Linux, Docker Compose, and Git. You can then clone down the repo and run `bash deploy.sh` and you should be good to go, as long as you also have SSL certificates on hand. Hope this helps, and feel free to open a new issue if you have trouble with this deployment system.
