### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by Bweekzzzzz** [successible/cleanslate#138]
How do I delete the bookmark permanently. It keeps reappearing after restarting my phone?

**Comment by paulzakin** [comment]
So, as far as I know, it is not a problem with Clean Slate. We do not even have the power to make something persistent like that! As such, it is something weird on your phone. And no one has ever reported something similar. Here's my suggestion for how to debug it.

Step #1:

Did you follow the instructions in this [video](https://www.youtube.com/watch?v=OJWsMojuVfk) for iOS and [these instructions](https://www.verizon.com/support/knowledge-base-180313/) for Android?

Step #2

Make sure your OS is updated? And that you do not have any weird settings toggled [like so](https://discussions.apple.com/thread/252515251).

Step #3

Try clearing you cache? Here is how to do it on [iOS](https://support.apple.com/en-us/HT201265) and [Android](https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DAndroid). 

Those are my best guesses - if that does not solve the problem you'll need to post on support forum for your phone. Best of luck!

**Comment by Bweekzzzzz** [comment]
Thanks. Did all that, but it still won’t delete permanently. When I reboot, it comes back. Thinking maybe cause I’m on iOS 17 beta 3. I’ll try again later. Thanks anyway man. 
    	Get Outlook for iOS
    
  

 From: Paul Zakin ***@***.***>Sent: Friday, July 7, 2023 9:44 PMTo: successible/cleanslate ***@***.***>Cc: Bweekzzzzz ***@***.***>; Author ***@***.***>Subject: Re: [successible/cleanslate] How to remove Clean Slate from my phone? (Issue #138) 
So, as far as I know, it is not a problem with Clean Slate. We do not even have the power to make something persistent like that! As such, it is something weird on your phone. And no one has ever reported something similar. Here's my suggestion for how to debug it.
Step #1:
Did you follow the instructions in this video for iOS and these instructions for Android?
Step #2
Make sure your OS is updated? And that you do not have any weird settings toggled like so.
Step #3
Try clearing you cache? Here is how to do it on iOS and Android.
Those are my best guesses - if that does not solve the problem you'll need to post on support forum for your phone. Best of luck!

**Comment by paulzakin** [comment]
The beta iOS then could totally be it - I only test Clean Slate on non-beta versions, so that makes sense!
