### ISSUE TITLE
SQL authentication failure

### ISSUE THREAD

**Issue by ados8** [successible/cleanslate#14]
I've built the 3 dockers in accordance with the instructions multiple times.
The logs are always the same for cleanslate server.
![image](https://github.com/successible/cleanslate/assets/49982433/46b41ecd-2fb9-4bce-b569-33af579b43b1)
The port is different because I have multiple other SQL dockers running without issue.
I can connect to the same database with the same username and password and it works.
![image](https://github.com/successible/cleanslate/assets/49982433/81fc927d-1c2a-43bd-a702-e9c233a34ee7)
The client portal works but obviously you can't login.
I've also tried building the dockers without the variables from the env (direct in the compose) and same issue.
Any chance the issue is in the build.

**Comment by ados8** [comment]
Found the problem, it's this line:
`HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@host.docker.internal:5432/postgres`
I had to specify the password removing the variable, also did it for `POSTGRES_PASSWORD:` and `HASURA_GRAPHQL_ADMIN_SECRET:` to be sure.

I don't use special characters in my SQL passwords so it can't be that.
The env file is in the cleanslate root directory with no name as specified.

**Comment by paulzakin** [comment]
Hmmmm...

So I think it because you are using a different port but never changed it in `HASURA_GRAPHQL_DATABASE_URL`. I updated the `README.md` to make the steps clearer. Can you run through the newly improved **How do I host Clean Slate?** section again and see if that fixes your problem. 

If it does not, please share the `custom.yml` and I'll see if I can help debug further. Thanks!

**Comment by ados8** [comment]
Sorry the line was copied from the compost in Github as my modified line had my password.
I did set the custom port and the logs showed it was failing to authenticate and thus was reaching the database.

On a side note before I close this.
The app is excellent, simple and most importantly self hosted.
Will there be other tracking measures such as carbohydrates and fat.
I used to use MyFitnessPal and it's the biggest wish for the Cleanslate app.

**Comment by paulzakin** [comment]
So, the app is designed for people who struggle with other apps, and want to lose weight. And the more things they have to track, the more they can get overwhelmed or feel like they have blown a target when they miss something. So it is definitely not a core feature for us, as we consider carbohydrates and protein really the only numbers worth tracking. 

However, you’re not the first person who has asked this, so we may end up adding it by the feature flag, giving users who want the control, such as yourself more options. So I’ll make a new ticket and you can subscribe to it for notifications if I decide to implement it. 

https://github.com/successible/cleanslate/issues/15
