### ISSUE TITLE
Calorie/Protein manual adding missing 

### ISSUE THREAD

**Issue by sgomez92** [successible/cleanslate#146]
It seems the option to add calories/Protein manually (similar to calories burned on exercise) has disappeared. I've found that I have access to that feature at the start of the day when no other food has been loaded but it disappears as soon as you add one item to the list.

**Comment by paulzakin** [comment]
Hmmm… I cannot replicate the behavior. Can you first try deleting the app, clearing your cache, and reinstalling it and trying again? If that doesn’t work, can you send me some GIFs of the issue? thanks!

**Comment by paulzakin** [comment]
OK, closing this pending further feedback. Feel free to reopen as needed!
