### ISSUE TITLE
First login on Setup - where to get Hasura Token

### ISSUE THREAD

**Issue by sodalimes** [successible/cleanslate#150]
I'm using docker on Windows and have cleanslate running. I'm confused where to get the token from? I have created an account, access token and project for the URL in Hasura cloud - but I don't think that is necessarily what is required for a local install of clean slate.  

Any help would be greatly appreciated.

**Comment by paulzakin** [comment]
So, first off, this project has nothing to do with Hasura Cloud. The version of Hasura used for Clean Slate is run locally. 

By token, do you mean HASURA_GRAPHQL_ADMIN_SECRET? That value is in your .env? 

If you mean the token you use to login, you need to go to the Hasura console (locally) and create the user. It is Step 5 in How do I host Clean Slate?

Hope that helps!

**Comment by sodalimes** [comment]
Thanks! I have set a random gen for the HASURA_GRAPHQL_ADMIN_SECRET and followed the steps 1-4 including the custom locations for NGINX as well as the bash deploy.sh. 

I see in the graphql-server logs, Environment variable HASURA_GRAPHQL_JWT_SECRET: Error in $: not enough input

Do you know how I can fix that issue? Thanks!

**Comment by paulzakin** [comment]
Your JWT_SIGNING_SECRET in your .env I do think is long enough - make sure it is 50 characters or more?

**Comment by sodalimes** [comment]
Thanks, I've increased it to 128 characters and still receive that error. I've tried including and excluding special characters and there's not a change.

**Comment by sodalimes** [comment]
I've also removed and re-created the docker containers, volumes and databases to make sure it's a fresh as possible.

**Comment by paulzakin** [comment]
Hmmmm - I looked through the previous issues. We have one that matched your issue: https://github.com/successible/cleanslate/issues/38. They changed from Ubuntu to Debian and it worked. TLDR: I just think your HASURA_GRAPHQL_JWT_SECRET is not being set properly in deploy.sh for the docker-compose.yml to consume. 

I just commited to `main` with a possible fix. So you can follow Steps 1-4 again and see if that solves your problem. The main difference is I'm forcing everyone to specify  HASURA_GRAPHQL_JWT_SECRET explictly in the .env now

**Comment by paulzakin** [comment]
Oh, and please make sure your version of Docker and Docker Compose is the most update to date it can be. That could be another problem. You can post the versions you are using now and the ones after you update.

**Comment by sodalimes** [comment]
Thanks for the app update and the modified instructions. Everything is working good now, I appreciate your help.
