### ISSUE TITLE
No Matching Profile Found

### ISSUE THREAD

**Issue by hollowpnt92** [successible/cleanslate#151]
Release Version: v2.25.0

I am receiving a "No Matching Profile Found" error when trying to login with my appID. I am not able to find anything in the container logs that could point me why this is happening. 

I confirmed that I am able to connect the database with passwords provided in .env file using pgadmin. 

I am able to create a new user (see screenshot) with Hasura 
![image](https://github.com/user-attachments/assets/7e08ab44-1983-4799-b96a-854738822fd9)

I am using Caddy as my reverse proxy to my external domain but I receive the same error when hitting the client frontend directly from my network. 

Attached are my container logs. 

[_graphql-server_logs.txt](https://github.com/user-attachments/files/16645538/_graphql-server_logs.txt)
[_database_logs.txt](https://github.com/user-attachments/files/16645539/_database_logs.txt)
[_client_logs.txt](https://github.com/user-attachments/files/16645540/_client_logs.txt)
[_authentication-server_logs.txt](https://github.com/user-attachments/files/16645541/_authentication-server_logs.txt)

**Comment by hollowpnt92** [comment]
![image](https://github.com/user-attachments/assets/3915df76-c44b-44ea-8565-64ce97e40c83)
 my auth server endpoint is showing up as well

**Comment by paulzakin** [comment]
In Step 2 of the How do I deploy Clean Slate. Make sure the .env is as outlined. It’s possible the two variables concerned with the JWT do not match. If that still doesn’t work I will try to replicate.

**Comment by hollowpnt92** [comment]
This is my current .env config 
![image](https://github.com/user-attachments/assets/6802039e-b50b-4693-8af9-d7ce2605f7e1)

**Comment by hollowpnt92** [comment]
its missing from the screenshot but I do have a postgrespass env set. Im able to auth to that manually just fine from pgadmin

**Comment by hollowpnt92** [comment]
Sorry after some more troubleshooting I was able to find my issue. My images had built with typos in the JWT secret and I didnt delete them so the image build wasn't happening again with the corrected secret. After rebuild I am able to login.

**Comment by paulzakin** [comment]
Excellent!
