### ISSUE TITLE
Make ports configurable

### ISSUE THREAD

**Issue by OG-Jons** [successible/cleanslate#155]
Right now, it seems the ports are hard-coded for the different tools (e.g 8080 for graphql)
This works in general, but in cases where the port 8080 is already used, it causes some trouble when self-hosting.

**Comment by paulzakin** [comment]
Yup, that is reasonable, I'll take a look this weekend

**Comment by paulzakin** [comment]
Ok, so if you look in the docker-compose.yml in the root, I added some environmental variables in #156 that should let you set custom ports. You really also have to change your nginx/caddy/etc. but I think this should solve your problem. Please reopen if it does not. Thanks!
