### ISSUE TITLE
Enhanced API Documentation for common tasks

### ISSUE THREAD

**Issue by ZachHoiberg** [successible/cleanslate#172]
Hello,

I have recently discovered this and started playing around with the API. I believe that, when combined with Grocy and Barcode Buddy, I can make a fully automated system that maintains my calories, reduces the available inventory I have in my fridge and pantry, and does so accurately and frustration free.

I find the documentation lacking examples of common tasks that Clean Slate handles when you do the following:

Scan a barcode and add a serving to your calories counted (What variables are pulled into the log itself via OpenFoodFacts?)
No mutation query examples

**Comment by paulzakin** [comment]
Ok, I've updated the README.md under the header: How can I make an API request to Clean Slate?

Hopefully that answers your question: you can reopen this ticket as needed!
