### ISSUE TITLE
Barcode Scanned Items Not Saving

### ISSUE THREAD

**Issue by WaleedTheLead** [successible/cleanslate#18]
As the title suggests, when I scan for items via the barcode scan feature and attempt to save the recipe, it does not save scanned items but only manually added items.

**Comment by paulzakin** [comment]
Ok, I will take a look and see if I can replicate it locally

**Comment by paulzakin** [comment]
Ok, great I can - I'll make a fix!

**Comment by paulzakin** [comment]
Resolved in #19
