### ISSUE TITLE
Barcode scanner doesn't show units when adding food

### ISSUE THREAD

**Issue by guidopetri** [successible/cleanslate#183]
After scanning an item's barcode, the units aren't shown (see screenshot below). Adding the food, then editing it allows you to change the units from e.g. `grams` to `serving`, but it'd be nice to only have to edit it once.

![image](https://github.com/successible/cleanslate/assets/18634426/82abf7c3-5686-4493-955f-73c696b6ba5a)

**Comment by paulzakin** [comment]
This seems reasonable and quick to do. Let me experiment for a bit.
