### ISSUE TITLE
[Bug] Recipe servings math seems odd

### ISSUE THREAD

**Issue by guidopetri** [successible/cleanslate#184]
Some of the recipe servings math seems off. In the screenshot below, I have `Boba mate` at one serving at the bottom at 97kcal, but at the top, with 2 servings, the same recipe shows 265kcal (~2.5x more instead of 2x more). I also attached a screenshot of the recipe, and of the `Mate` recipe backing it (it's using a recipe as a food). This latter one has something weird with the calorie density shown too (380 at the bottom vs 378 at the top right).

![image](https://github.com/successible/cleanslate/assets/18634426/8999320c-5544-47ce-86c0-7c4bb3d90209)

![image](https://github.com/successible/cleanslate/assets/18634426/3fa55868-e7dc-400a-bbc4-a7f9805dc1b0)
![image](https://github.com/successible/cleanslate/assets/18634426/8cb53917-ae8c-457f-b8a6-e546cbb3a7fe)

**Comment by guidopetri** [comment]
I think that when I switch it to 2 servings, the underlying recipe gets doubled as well - so 35 -> 70, + 62 = 132. Then doubling that on the `Boba mate` level yields the 265 we observe.

**Comment by paulzakin** [comment]
Yup, that was a good find - patched!

**Comment by paulzakin** [comment]
Also, did you know that you can add recipes with units directly. For example, you are using the label to represent a unit but use the actual unit as well. I altered the new recipe and new custom food pop up to make that clearer :)

**Comment by guidopetri** [comment]
Hmm, I think I see that option but it looks like only `cup/tbsp/tsp` and `gram/oz/lbs` are supported, is that right? Since this is a beverage it doesn't quite fit any of the volume units very well.
