### ISSUE TITLE
Save barcode-scanned items into foods

### ISSUE THREAD

**Issue by guidopetri** [successible/cleanslate#185]
I find myself often having the same (processed) foods over and over, e.g. a can of iced tea. It'd be convenient to (optionally?) save the barcode-scanned items into `Food`s so that next time I have a can of iced tea, I don't have to scan the barcode again - just look up the name of the item that was found and add it.

**Comment by paulzakin** [comment]
Let me think about both this one and the related issue for recipes

**Comment by paulzakin** [comment]
I think this is a good idea - but not totally convinced - do you have an interface in mind. Currently, when you scan a barcode, it will pop up the window to log it, now with units, thanks to #188.

What would be the next screen?

**Comment by guidopetri** [comment]
Haha, you are too fast for me. Let me see what it looks like on the official deployment but I'm sure whatever you came up with is sensible. Thanks!

**Comment by guidopetri** [comment]
Alright, finally got around to testing on the official deployment - this looks great! Thanks so much for the quick turnaround, and for all your work creating the app!
