### ISSUE TITLE
Barcode scanning into recipes

### ISSUE THREAD

**Issue by guidopetri** [successible/cleanslate#186]
Last issue for now, promise :)

When creating a recipe, it seems we can only add either a basic food or a saved custom `Food`. However, some items aren't available as basic foods but are used in recipes - e.g. if I'm making a hotdog, I might want to scan the hotdog/sausage package to create a `Hotdog` recipe that includes the sausage + the bread. It'd be helpful to be able to barcode scan in the recipe creation view so that that scenario is possible, without having to (manually) create a custom `Food` for the sausage first to then add to the recipe.

**Comment by paulzakin** [comment]
Closing in favor of #185

**Comment by paulzakin** [comment]
Realize that this is actually separate and probably worth doing
