### ISSUE TITLE
Slider for changing food amount

### ISSUE THREAD

**Issue by mgrzaslewicz** [successible/cleanslate#192]
Currently in order to change amount of food, you have to edit, type in new value, save it.
It would be great to have a slider on the list to easily adjust amount.
This way it would be easy to adjust e.g. "a bit more chicken and less bread" to achieve a calories/protein goal

**Comment by mgrzaslewicz** [comment]
Oh, and I forgot to mention - I love the idea for this project :) The app is already useful

**Comment by paulzakin** [comment]
Hmmmmmm. Can you give me a sketch or screenshot of what that might look like? Would it exist along with the input or replace it? Would there be a way to toggle between the two? I think it could be a cool idea but I need more details :)

**Comment by mgrzaslewicz** [comment]
@paulzakin 

> I think it could be a cool idea but I need more details :)

Sure :)

I'll start with a big picture of how I perceive a food tracking app both from UX perspective and as a software engineer:
- it's meant to help achieving a goal: lose, maintain or gain weight
- I don't want to reactively track what I just ate. I want to also plan (a bit - thinking of current day ahead max is fine)
- Every additional input or step is an obstacle to keep tracking food

In an ideal world, 0 steps would be necessary to know how much and what one needs to eat to achieve a goal. You already have a quite good input detector and processor: your eyes and brain for processing. It's not enough however, maybe using app for a long(er) time would make help have good eyeballing precision.
In a pragmatic world, a number of steps close to zero to provide an input in an app would be great.

As a software engineering I don't want to repeat any manual steps over and over. Also having good defaults for skipping any inputs is a good thing.

And now let's jump back to slider.

Something like that would allow quickly adjust amount. For grams it would move by a single gram.
Full-width maybe for easier finger movements.
![image](https://github.com/user-attachments/assets/513a89b9-345d-4167-9316-d5ea964ac87a)

Range slider could be also attached to a dialog where food is added.

To get close to 1 step to add a food:
- User taps add food icon
- A list of recent/favorites/most frequently consumed foods shows up below the keyboard input
![image](https://github.com/user-attachments/assets/4c82d785-a9a8-42cf-a874-9d425b8937a4)
- An input with range slider underneath appears. It would already be filled with a reasonable default (based on what is another discussion: last added, custom setting etc.)
![image](https://github.com/user-attachments/assets/fd131ef3-131f-4918-a53b-ea386d0126fe)

WDYT?

**Comment by paulzakin** [comment]
Thanks for elaborating!

Hmmmmm. It is a cool idea with merit. However, the sliders add to much new “stuff” to the interface to my liking for a thing no user has really complained about. And sliders have bit of a “meh” reputation for [UX](https://www.nngroup.com/articles/gui-slider-controls/). Hence, I will not be implementing the sliders. 

The other aspect of your suggestion is interesting. Would showing you the list of foods you added for that day on the model/popup and having the default amount filled to what you added before be what you are looking for? We would only use the “frequency” data from the day, and not before. After all, the whole point of the app is each date is a fresh start!

**Comment by mgrzaslewicz** [comment]
> sliders have bit of a “meh” reputation for [UX](https://www.nngroup.com/articles/gui-slider-controls/).

Valid points about slider. I'm currently using apps on mobile and have exactly the mentioned issues like thumb hovering the value and sometimes problem to make a tiny movement to adjust precise value.
However it's still faster than typing - for a very specific reason. With a few movements you can adjust amount of multiple foods. And sometimes you have to workaround the "meh" problems.
Maybe an editable number input for quick edit?

I started with asking about a slider, but it's a [XY](https://en.wikipedia.org/wiki/XY_problem) problem.
What I'm really trying to figure out is "with minimum effort, how to adjust any amount of food already added to the daily plan so I can cut out carbs/fats and add more protein?" (it might be any other combination of what user might increase/decrease).
This way user can explore via UI the proper amount of what to eat and UI helps to achieve that.


> After all, the whole point of the app is each date is a fresh start!

How about a checkbox like 'default amount for this food'?

**Comment by paulzakin** [comment]
OK, these are interesting ideas but I think on the whole they just add too much complexity and “new things“ to the interface to justify, especially since you are the first one who has brought them up. 

I’d be happy to reopen this in the future if several other people ask about this, which has happened for other features we have done. Thanks again!
