### ISSUE TITLE
Track weight

### ISSUE THREAD

**Issue by fabiiretro** [successible/cleanslate#206]
Just spun up my self-hosted version of this app and thought about also tracking my weight.
I wouldn't say it's against your article on weight loss (https://cleanslate.sh/weight-loss), but wanted to have a brief discussion before I started thinking about implementation.

Is this a feature anyone else would want or you had thought about already?
I'd like to at least know that I'm not the only person to maybe want this before I potentially butcher your app (that is, if I even manage to do anything. SQL scares me :stuck_out_tongue:).

Forgot to mention that "out of scope" is also acceptable, since the slogan is "Track *food* without judgment."

**Comment by paulzakin** [comment]
Thanks for the suggestion! 

Tracking weight in an app designed to be nonjudgmental about tracking food gets a little tricky and can trigger black-and-white thinking. Hence, unfortunately, I would consider this out of scope. 

Instead, I would use a weight tracking app in conjunction with Clean Slate. For example, Happy Scale in iOS or Libra in Android. Thanks!
