### ISSUE TITLE
Issues Authenticating After Portainer Deployment

### ISSUE THREAD

**Issue by lmath56** [successible/cleanslate#210]
Hello, 

I am interested in hosting CleanSlate for myself. I have a Docker host (Alpine Linux) and use Portainer to manage it. 
I used the instructions [here](https://github.com/successible/cleanslate#how-do-i-host-clean-slate) but did it a but different as I am doing it via Portainer.

I copied and created the `.env` file with 3x keys over 50 characters. I left the ports as default.
I then copied the [Dockercompose ](https://github.com/successible/cleanslate/blob/main/docker-compose.yml) file and created a new stack, importing the `.env` file to the stack.

Once done I was able to log into Hasura with the `HASURA_GRAPHQL_ADMIN_SECRET` and followed the instructions to create the new profile, copying the `apiToken`. 

When entering the `apiToken` into the app, it gives an error that it is incorrect and to be sure that I am not using the `authToken`.
I have quadruple checked that I am using the `apiToken`

There are no errors in the logs of any of the containers.  

I did not use the `bash deploy.sh` file, and I have a separate proxy / cert manager so I believe I do not need to configure Caddy / Nginx.
The only changes I made to the Dockercompose file were:

- Remove the database volume and change it for a bind mount - to a local directory on the docker host.
- Changed the below to bind mounts as well, where I cloned the contents for each folder from this repo.
```bash
    volumes:
      - ./migrations:/hasura-migrations
      - ./metadata:/hasura-metadata
   ```

I have tried re-deploying this a few times, and still getting the same results. I cannot get past the client login page. 

Does any part of my process stand out as an issue?

**Comment by paulzakin** [comment]
Nothing seems wrong to me but I have never tried Alpine Linux or Portainer. That error can occur when the internal communication between the container running Hasura and the one running Express is “off” somehow. My guess is Portainer is the culprit.

I would say start by deploying it just by Alpine Linux and Docker Compose - not via Portainer and seeing if that solves the problem? There are too many variables for me to really figure it out. Of course, you can always just use our free instance as well if you cannot figure it out. I’m gonna close this issue, but feel free to reopen if you made progress. Sorry for not being able to figure it out from the available information.
