### ISSUE TITLE
Allow specifying serving count per recipes and calculate per-serving stats

### ISSUE THREAD

**Issue by JiddoDev** [successible/cleanslate#32]
A lot of recipes will be for multiple servings, especially when doing meal prep, and it would be great if users could input the recipe as cooked and specify the number of servings per recipe and have the app automatically calculate the calorie/protein stats for each serving. 

I'm currently working around this by using "X cup per recipe" as "X servings per recipe" and tracking 1 cup of the recipe, but this isn't the most intuitive. 

Allowing for custom (user defined) unit labels would also be an option.

**Comment by paulzakin** [comment]
Ok, that is a very reasonable request and good idea!

I created the feature in this pull request - it should be live in 30 minutes - I'll close this issue when that is the case. Feel free to reopen if you have feedback on the feature!

https://github.com/successible/cleanslate/pull/33

**Comment by paulzakin** [comment]
Ok, it is live - let me know what you think

**Comment by JiddoDev** [comment]
Nice, it seems to work really well! Thanks for the quick turnaround.

I did notice that the resulting caloric density value for individual servings now ends up being unexpectedly low. I'm not sure how caloric density should be calculated, but I'd intuitively expect it to be the same regardless of the servings that a recipe is divided into.

**Comment by paulzakin** [comment]
Yup, that makes sense - I’ll take a look

**Comment by paulzakin** [comment]
Ok, yup - that was a bug - should be fixed now - good catch!
