### ISSUE TITLE
WebSocket connection failed

### ISSUE THREAD

**Issue by rajkumaar23** [successible/cleanslate#42]
I am trying to self host CleanSlate, and the app crashes post login.

This is what I see on the browser console:
```
WebSocket connection to 'wss://<redacted-domain.com>/v1/graphql' failed: There was a bad response from the server.
```

And these are the server logs:
```json
{
   "detail.http_info.content_encoding":null,
   "detail.http_info.http_version":"HTTP/1.0",
   "detail.http_info.ip":"<REDACTED>",
   "detail.http_info.method":"GET",
   "detail.http_info.status":200,
   "detail.http_info.url":"/v1/graphql",
   "detail.operation.error.code":"invalid-headers",
   "detail.operation.error.error":"Missing &apos;Authorization&apos; or &apos;Cookie&apos; header in JWT authentication mode",
   "detail.operation.error.path":"&#x24;",
   "detail.operation.raw_query":"",
   "detail.operation.request_id":"2338fbce-263d-40c7-9ffa-027609bff628",
   "detail.operation.request_mode":"error",
   "detail.operation.response_size":117,
   "detail.operation.uncompressed_response_size":117,
   "detail.request_id":"2338fbce-263d-40c7-9ffa-027609bff628",
   "level":"error",
   "span_id":"31006d54753b4345",
   "timestamp":"2024-01-09T22:26:24.548+0000",
   "trace_id":"f54beb7d98d7e34cf8aabdee1f5df1fa",
   "type":"http-log"
}
```

And my localStorage does have the 'token' set appropriately. I am not sure what's wrong here. Can you help? Let me know if you need further information.

**Comment by paulzakin** [comment]
Hmmmm…. 

What does your .env look like? And can you log into the Hasura console and it works normally?

What browser and you using and what OS are you running Clean Slate on. And what reverse proxy are you using? Basically something is wrong with how the client is transmitting the JWT to the server, which seems setup dependent, as no one else has had this error before. 

This is the key 

 "detail.operation.error.code":"invalid-headers",
   "detail.operation.error.error":"Missing &apos;Authorization&apos; or &apos;Cookie&apos; header in JWT authentication mode",
   "detail.operation.error.path":"&#x24;",

I need to see the headers that are being sent by your browser/client to the server basically

**Comment by rajkumaar23** [comment]
> What does your .env look like? And can you log into the Hasura console and it works normally?

The .env has only those 3 vars mentioned in the README:
- POSTGRES_PASSWORD=""
- NEXT_PUBLIC_HASURA_DOMAIN=""
- HASURA_GRAPHQL_ADMIN_SECRET=""

And yes, there's no problem on the console. I was able to login and create a row for the `authId`.

> What browser and you using and what OS are you running Clean Slate on. And what reverse proxy are you using? Basically something is wrong with how the client is transmitting the JWT to the server, which seems setup dependent, as no one else has had this error before.

- Browser: Safari / Brave (tried on both)
- OS: `Linux raspberry 6.1.0-rpi4-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.54-1+rpt2 (2023-10-05) aarch64 GNU/Linux`
- Rev Proxy: nginx with the below config ⬇️ 
```nginx
server {
    listen 443 ssl;
    server_name <REDACTED>; 

    ssl_certificate /etc/letsencrypt/live/<REDACTED>/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<REDACTED>/privkey.pem;

    location /v1 {
        # API (Hasura)
        proxy_pass http://localhost:8080;
    }

    location /v2 {
        # API (Hasura)
        proxy_pass http://localhost:8080;
    }

    location /console {
        # Admin panel (Hasura)
        proxy_pass http://localhost:8080;
    }

    location /healthz {
        # Health check (Hasura)
        proxy_pass http://localhost:8080;
    }

    location / {
        # Static files (Clean Slate)
        proxy_pass http://localhost:3000;

        add_header Referrer-Policy "strict-origin";
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload;";
        add_header X-Content-Type-Options "nosniff";
        add_header X-Frame-Options "DENY";
        add_header X-XSS-Protection "1; mode=block;";
    }
}
```

> I need to see the headers that are being sent by your browser/client to the server basically

And here's the socket request:
```
GET /v1/graphql
Upgrade: websocket
Pragma: no-cache
Sec-WebSocket-Key: 2cAKWqBmSMjLjOZj1aAvdQ==
Sec-Fetch-Site: same-origin
Sec-WebSocket-Version: 13
Sec-WebSocket-Extensions: permessage-deflate
Cache-Control: no-cache
Sec-WebSocket-Protocol: graphql-ws
Sec-Fetch-Mode: websocket
Origin: REDACTED
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15
Connection: Upgrade
Sec-Fetch-Dest: websocket
```

**Comment by paulzakin** [comment]
So all of that looks fine - I need to see the logs in the browser development console (network) tab for the requests to /v1/graphql - I think something is wrong with the authorization header being sent to the browser from the server or it is being omitted - it could be a problem with nginx?

Either way, Hasura is complaining that an authorization header is not being sent from the client to the server 

Are there any errors in the browser console?

**Comment by paulzakin** [comment]
And could you try caddy and the caddyfile in the readme - that might help eliminate nginx as a source of the problem

**Comment by rajkumaar23** [comment]
So, the request I pasted in my last comment was generated using the “Copy as HTTP Request” option from the network tab. And it looks the auth header is not even sent, which makes me think it’s a client side issue. 

Yes, there’s a repeated error on the console saying:
> WebSocket connection to 'wss://<redacted-domain.com>/v1/graphql' failed: There was a bad response from the server.

Since I have multiple other virtual hosts running on the same machine with nginx, installing caddy doesn’t seem like a viable option.

**Comment by paulzakin** [comment]
So, the problem would not show up in the headers. It is a 101 Switching Protocols request. The main instance, `app.cleanslate.sh`, for example, does not even send an `Authorization` header and it works fine. 

Instead, you need to look in the `Messages` tab and see what is happening. In Chrome at least, if you click the Network tab, click the `graphql` request and you will see four tabs: Header, Messages, Initiator, and Timing. You want the Messages tab. 

  And within that, the first row of it which should say `connection_init`. That is ultimately where the `Authorization` header is passed. I need to see that information.

**Comment by paulzakin** [comment]
And if that information does not solve it, outside of spinning up a fresh server with Caddy and seeing if that solves it, my remaining debugging options are kind of limited :(

**Comment by rajkumaar23** [comment]
Okay, I seem to have figured it out. It was an issue with my nginx config. I forgot that I had to explicitly set the Upgrade and Connection headers (for the WS tunnel to work) as follows:

```nginx
location /v1 {
  # API (Hasura)
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection 'Upgrade';
  proxy_set_header Host $host;
  proxy_pass http://localhost:8080;
}
```

Thanks for your help! Now, onto playing with a clean slate :)

**Comment by paulzakin** [comment]
Awesome, I’ll make a note for that in the readme.md :)

**Comment by paulzakin** [comment]
Ok, added! This was a good exercise for `nginx` users:

And just a brief aside, this header:

`add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload;";`

I've updated it to remove the preload directive by default, so it is now just this:

`add_header Strict-Transport-Security "max-age=31536000; includeSubDomains;";`

You may or not want to [preload your domain](https://stackoverflow.com/questions/71377849/hsts-preload-meaning), just thought I would add that disclaimer.

**Comment by paulzakin** [comment]
Oh, forgot to mention, I updated both the Caddy and nginx configuration with the recommended content-security-policy and permission-policy headers - it is probably worth updating your nginx configuration with those values

**Comment by rajkumaar23** [comment]
Sure, thanks for letting me know!

**Comment by paulzakin** [comment]
Sure - just made my final update to the config for the night and I'm officially done lol - feel free to use it whenever. And let me know if you have any feature suggestions (in a different issue). Thanks!

**Comment by remus-selea** [comment]
I wanted to try this out. I'm using [SWAG](https://docs.linuxserver.io/images/docker-swag/) as a reverse proxy. 
I've put together the proxy-conf below, but I'm getting `WebSocket connection to 'wss://cleanslate.example.com/v1/graphql' failed: ` after logging in.

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name cleanslate.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth (requires ldap-location.conf in the location block)
    #include /config/nginx/ldap-server.conf;

    # enable for Authelia (requires authelia-location.conf in the location block)
    #include /config/nginx/authelia-server.conf;

    # enable for Authentik (requires authentik-location.conf in the location block)
    #include /config/nginx/authentik-server.conf;


    location /v1 {
        # API (Hasura)

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'Upgrade';
        proxy_set_header Host $host;
        set $upstream_app nixos-clownfish.home.arpa;
        set $upstream_port 8085;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

    location /v2 {
        # API (Hasura)

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app nixos-clownfish.home.arpa;
        set $upstream_port 8085;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

    location /console {
        # Admin panel (Hasura)

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app nixos-clownfish.home.arpa;
        set $upstream_port 8085;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        add_header Content-Security-Policy "";
    }

     location /auth {
        # Authentication server (Express.js)

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app nixos-clownfish.home.arpa;
        set $upstream_port 3007;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

    location /healthz {
        # Health check (Hasura)

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app nixos-clownfish.home.arpa;
        set $upstream_port 8085;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }


    location / {
        # Static files (Clean Slate)

        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable for ldap auth (requires ldap-server.conf in the server block)
        #include /config/nginx/ldap-location.conf;

        # enable for Authelia (requires authelia-server.conf in the server block)
        #include /config/nginx/authelia-location.conf;

        # enable for Authentik (requires authentik-server.conf in the server block)
        #include /config/nginx/authentik-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app nixos-clownfish.home.arpa;
        set $upstream_port 3006;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

**Comment by paulzakin** [comment]
So @remus-selea I am not sure - we really only support “vanilla” nginx or Caddy - I have not used SWAG before - unfortunately I will not be much help here :(
