### ISSUE TITLE
Duplicate custom recipe clears all the input

### ISSUE THREAD

**Issue by rajkumaar23** [successible/cleanslate#43]
When trying to add a **custom recipe** with an existing name, all the ingredients I entered vanishes when the error is shown. This behavior does not look ideal. Interestingly, this does not happen when adding a duplicate **food**.

https://github.com/successible/cleanslate/blob/9c14af0d749bb565b1de8b6625781e8a1de1575e/src/helpers/handleError.ts#L23

A fix would be to still have the toast but retain all the original inputs, so that only the recipe name will have to be modified by the user.

**Comment by rajkumaar23** [comment]
Another improvement would be to show the same prompt as below **when Esc key is pressed** during creation of a recipe. 

As of now, all the information is gone when Esc is pressed.

![Screenshot 2024-01-12 at 5 07 45 PM](https://github.com/successible/cleanslate/assets/37476886/894eed3c-3c8a-49d4-adca-6cadb0818f46)

**Comment by paulzakin** [comment]
Let me play around with it, but that’s a good idea

**Comment by paulzakin** [comment]
Implemented - good suggestion!
