### ISSUE TITLE
Esc. key closes the modal without a prompt

### ISSUE THREAD

**Issue by rajkumaar23** [successible/cleanslate#44]
An improvement would be to show the same prompt as below **when Esc key is pressed** during creation of a recipe (and at other similar places). 

As of now, all the information is gone when Esc is pressed.

![Screenshot 2024-01-12 at 5 07 45 PM](https://github.com/successible/cleanslate/assets/37476886/894eed3c-3c8a-49d4-adca-6cadb0818f46)

**Comment by paulzakin** [comment]
Another good idea, let me play around with it

**Comment by rajkumaar23** [comment]
On a side note, the current prompt appears even when I do not make any change after opening the  edit modal for a recipe (and just try to close).  

It may be a good idea to track in a boolean if/when any change is made, and then show the confirmation popup only if true.

**Comment by paulzakin** [comment]
Implemented both - good suggestion!
