### ISSUE TITLE
Store history of quick adds

### ISSUE THREAD

**Issue by rajkumaar23** [successible/cleanslate#47]
Currently all the quick adds sum up and show as a single number which makes it harder to go back and edit in case of a typo. 

May be, storing each of the additions as part of a list would be a good enhancement.

**Comment by paulzakin** [comment]
So that I will not do because it will add a lot of lines to the interface. 

If you were at (500, 100) and accidentally added 50, you can add -50. Not ideal, but it’s worth keeping the interface not very cluttered.

thanks for the suggestion, though!
