### ISSUE TITLE
Description for quick add

### ISSUE THREAD

**Issue by mkopinsky** [successible/cleanslate#54]
First off - thanks for a great app! Seeing something with crisp, minimalist design is a huge breath of fresh air.

I love the simplicity of quick add - just being able to enter two numbers from the nutrition facts is *so* much easier than needing to search through some database like some other apps require. The downside (as seen by #47) is that you can't see the log of what you ate today, only the bottom line number. Sometimes it would be good to a) have the app remind me where the (quick-add) calories came from (it already does that for the non-quick-add foods) and b) if I eat more of that food, having it in the list makes it easier to just increase the numbers (or decrease or delete) rather than needing to look at the nutrition facts again.

What I'm imagining or hoping for is an Almost-As-Quick-Add, where I could enter, say, `130<tab>3<tab>crackers<enter>` and it would add an item to the day's list with that description. I could go in later and edit to 180 and 5 if I eat more crackers. Admittedly, the quick add entry UI wouldn't be as smooth with 3 fields than with 2, and I could understand putting it behind a feature flag. I don't agree with your objection in #47 to having a long list - the list UI will already contain a long list if I use foods from the database; having quick add items in the same list wouldn't make it appreciably longer.

Thanks for the consideration!

**Comment by paulzakin** [comment]
So, totally open to the idea! But maybe I need a sketch or something? Having trouble visualizing it lol

**Comment by mkopinsky** [comment]
Entry form has a 3rd input. (I'd probably change it so the widths are 25%, 25%, 50% instead of 33/33/33.
![image](https://github.com/successible/cleanslate/assets/591435/9b4c5540-a493-426a-8049-09e88fa8b2b4)

Food list has a generic icon that's used no matter what description is entered. The serving size doesn't show up.
![image](https://github.com/successible/cleanslate/assets/591435/26a2db18-0a32-4083-9002-d783319be154)

**Comment by paulzakin** [comment]
So its "cookies" just a plain text tag, and not linked to anything in the database? 

And currently quick does not show a "log" of what you quick added to save space in the interface. I guess I could have the pencil open a pop-up / modal of a log of quick adds?

**Comment by paulzakin** [comment]
So this was referenced by someone else in #47 - to essentially show a "history" of quick adds. I think this feature would require that as a side effect.

**Comment by mkopinsky** [comment]
correct, "cookies" is free text entry.

What I'm proposing (which was also proposed in #47) is that at least these quick add items would show up in the main list *instead of* in the quick add numbers up top. One valid option would be to keep the "truly quick" quick adds as just numbers (which could be increased and decreased, but don't have a log/list) but if you include a description (or toggle a feature flag) each quick add becomes an entry in the list.

**Comment by paulzakin** [comment]
Hmmmmm....

So I want the default behaviour to be the simplest possible option. But, I'm happy to build a feature flag that does what you suggest - a third column for text tag and the quick win being moved as a list to the main panel, rather than aggregated in the panel above. Do you think that would satisfy what you want?

**Comment by mkopinsky** [comment]
Yes!

Does feature flag mean a toggle in the settings panel?

**Comment by paulzakin** [comment]
Indeed!

**Comment by mkopinsky** [comment]
Sounds great!

**Comment by paulzakin** [comment]
Ok, so worked for a couple of hours today on this - it actually was more work than I thought, because it will require some new models and an interface overhaul. Made good progress today on it, just don't expect it immediately!

**Comment by paulzakin** [comment]
Added! Really nice idea - I actually made it the default behaviour I liked it so much :)

**Comment by mkopinsky** [comment]
Amazing! This looks great... but only in an incognito window with no localStorage. In my main browser (Firefox desktop including in a fresh tab, and Chrome PWA) I'm getting a browser error.

The error is:
```
TypeError: t is undefined
    ir calculateMacros.ts:307
    sJ Numbers.tsx:58
    React 7
    x scheduler.production.min.js:13
    T scheduler.production.min.js:14
    95507 scheduler.production.min.js:14
    Webpack 18
```
From dev tools it seems that the props being passed to the Numbers component include `quick_logs: undefined` (also `exercise_logs: undefined`, though idk if that's a problem) but calculateMacros is expecting it to be an array.

If this will self-resolve tomorrow with a clean slate this can obviously be ignored, and presumably I can just clear localStorage and get past this, but if it's broken tomorrow it'll presumably affect other users as well.

**Comment by mkopinsky** [comment]
Also, one other suggested tweak: the "It's a new day! Here are some things to do" shows up even after adding quick logs. Ideally, as soon as there's either a quick log that message should disappear.

**Comment by paulzakin** [comment]
Added your suggestion!

And yup, that's a gnarly bug. I have not added a new table in forever, and I guess the localStorage cache did not like that. Hard to reason about on local development. When the server worker updates with any future, new version of Clean Slate, I now clear the cache as a precaution. 

But the error you found should be fixed and should naturally "fix itself" tomorrow for everyone, when the client resets the localStorage. However, if you want to fix it in advance - you'll need to clear the localStorage, as you pointed out.

If this occurs tomorrow, let me know. 

And thanks so much for the prompt reporting - having an extra pair of eyes is super helpful!!

**Comment by mkopinsky** [comment]
Thanks for the quick fix!

I'll report back tomorrow if it's still broken.
