### ISSUE TITLE
Native app instead of PWA?

### ISSUE THREAD

**Issue by mkopinsky** [successible/cleanslate#55]
Would you consider publishing this to the app store(s) so it could run natively rather than as a PWA? For me (Firefox on Android) the PWA sometimes glitches out - e.g. opens to an empty screen, and I need to close and reopen. I don't think this is the fault of the app at all, and I think it's great to have PWA as an option, but I wonder if wrapping up the PWA as a native app published to the Google Play Store would solve this.

**Comment by paulzakin** [comment]
Huh, FireFox on Android. That is one I never tested - does the error occur on Chrome, out of curiosity? 

But basically, what you are saying is if the app was bundled on the Google Play store as a PWA (doable, I think), that would be your preferred option? Given that I'd imagine that the bundled PWA on the Play store uses Chrome, that seems like it would eliminate the bugs from a nicher browser?

**Comment by mkopinsky** [comment]
I can't reliably reproduce the issue. I suspect it's when either the OS kills the browser process, or Firefox kills the tab or removes it from memory, or something like that. I'll play around and try Chrome and report back.

**Comment by paulzakin** [comment]
Ok, that would be great, thanks!

**Comment by paulzakin** [comment]
Feel free to reopen if you can replicate!
