### ISSUE TITLE
Searching Open Source Database via text

### ISSUE THREAD

**Issue by AnthonyOro** [successible/cleanslate#56]
I would love to be able to search the Open Food Facts data base with text rather than barcode!

Also, it'd be nice to be able to summon previously eaten foods. Like if I'm drinking a specific brand of protein shake every day, I'd prefer to not have to scan the barcode each time.

**Comment by paulzakin** [comment]
The first one is clever! Never occured to me to treat the Open Food Facts database like that. Maybe we could put it as an option when the barcode modal pops up to scan by camera or search by text?

The second one we already implemented, I believe. Do you not see "Create a custom food from this scan?" when you try to scan a barcode? That will enable you to create that protein powder as a custom food.

**Comment by paulzakin** [comment]
Having thought more about it, the open food facts database is massive! I think adding it would add a level of complexity to the search interface that is not worth the benefit - so I’m going to close this. Thanks for the suggestion though!
