### ISSUE TITLE
Latest master is broken?

### ISSUE THREAD

**Issue by alex4108** [successible/cleanslate#62]
On latest commit of master: https://github.com/successible/cleanslate/commit/ac376c7ad29ee2a6c53c285d75b4d9b20f8a87fb
When I run the instructions for docker-compose / deploy.sh locally, I'm met with a /build missing some artifacts

>/build # ls
service-worker.js        service-worker.js.map    sw.js                    sw.js.map                version.txt              workbox-e4b65e41.js      workbox-e4b65e41.js.map

When I roll back to the build at this commit it works, I have index.html and more https://github.com/successible/cleanslate/commit/52a46102570a19cd0378d8d014b17bb128776b5c

**Comment by paulzakin** [comment]
This I cannot replicate - I just build locally on and on the production server to check - any more context you can give?

**Comment by mkopinsky** [comment]
Don't know if it's related to this but I'm getting a 404 on production

**Comment by paulzakin** [comment]
Yup, I see that - looking at it now

**Comment by paulzakin** [comment]
Ok, fixed! And I think that fixes your problem too @alex4108. 

(Please reopen if it comes back)
