### ISSUE TITLE
Calorie tracking resets after using barcode  scanner 

### ISSUE THREAD

**Issue by SirFuzzyWalls** [successible/cleanslate#62]
![Screenshot_20230315-151128](https://user-images.githubusercontent.com/39246204/225455323-016a331c-9754-4d38-908d-b21de04d905d.png)

Pretty much the title, after using the barcode scanner my calorie count reset and only subtracted the amounts added by the scan. 

As a note my calorie goal is set to 1950, as you can see the numbers on screen don't add up.

Other than that really loving the app!

**Comment by paulzakin** [comment]
Huh, weird!

**Comment by paulzakin** [comment]
So let me get this straight - you add like 500 calories worth of food or something and then use the barcode scanner and then it kinda resets everything else?

**Comment by paulzakin** [comment]
Ok, fixed it - that was a easy bug to squash. Let me know if that works for you. And thanks for reporting it!

**Comment by SirFuzzyWalls** [comment]
Thanks! I'll check it out again and see if it acts up again!

Cheers,
Simon McGraw
