### ISSUE TITLE
Control what time your app resets your calories

### ISSUE THREAD

**Issue by paulzakin** [successible/cleanslate#71]

**Comment by mkopinsky** [comment]
Yes, this would be great! I've had some... midnight snacks which I didn't log because I wanted it to count towards the previous day's calories instead of the next day's.

**Comment by paulzakin** [comment]
Yup, a Reddit user suggested this to me - we used to have it but it was buggy and I removed it - probably should take another swing at this.

**Comment by paulzakin** [comment]
After some thought, I have decided not to implement this right now. if more people ask, I’ll likely change my mind!
