### ISSUE TITLE
Issues with quick add exercise

### ISSUE THREAD

**Issue by mkopinsky** [successible/cleanslate#72]
Two issues:

1. If I add an exercise and leave the activity on Custom, it gets added as Baseball. Which not coincidentally is the first option in the Other section. I guess it's selecting baseball even though that section is hidden.
2. In the past, exercise calories got added to the denominator - so if I've eaten 1000/2000 and I add 500 calories of exercise, now I'm at 1000/2500. Now, it's subtracting from the numerator, so it shows as 500/2000.

**Comment by paulzakin** [comment]
Ok, looking at this now!

**Comment by paulzakin** [comment]
Ok, fixed both and deployed as v2.7.0 - thanks for the report!
