### ISSUE TITLE
Environment variables messed up for self-hosted deployment

### ISSUE THREAD

**Issue by alex-pub** [successible/cleanslate#75]
Hi,

I've just tried to set up a local, non-Firebase deployment of the current (head/v2.7.0) version and I think there might be two issues preventing it to run without modifications (at least I couldn't get it to work in a vanilla state).

The first one is out-of-order exporting of `HASURA_GRAPHQL_JWT_SECRET` in `deploy.sh` as it depends on `$JWT_SIGNING_SECRET` which is supposed to come from the `.env` file, however variables from `.env` are loaded only after it's evaluated resulting in an empty `HASURA_GRAPHQL_JWT_SECRET` (if you already didn't export the said variable in your local environment, that is). A quick fix is to just move `export $(xargs < .env)` one line up, before exporting the `HASURA_GRAPHQL_JWT_SECRET`, to give it a chance to load `$JWT_SIGNING_SECRET`.

The second one is an overlook on evaluating the `NEXT_PUBLIC_USE_FIREBASE` environment variable within `server.ts`. Namely, it's just loaded as-is, no additional evaluation, into the `useFirebase` const, and then is later used in `/auth/login` handler to disable the endpoint if `useFirebase` is, presumably, true/yes/1. However, since it's just a string, any non-empty value, including a "no" (the default from `deploy.sh`) will be evaluated as `true`, hence preventing the endpoint to work and always spewing 403 on login attempts. A quick fix is to just do a more complex evaluation (i.e. `if (['yes', 'true', '1'].includes((useFirebase ?? '').toLowerCase())) { ... }`) on the spot, but I'd advise rethinking of how to handle ENVs properly overall. I'm not well versed in the TS side of things, but I'm fairly certain there must be a competent environment variable handling library out there to help out with that.

Had I had more time, I'd set up a dev env. and propose the changes myself, but I've run out of time. Regardless, since I spent a bit of time investigating why it doesn't work, thought to share back with you/the community the potential issue.

Good luck with the project, a no-frills food tracker is quite a neat idea :)

Cheers,
A.

**Comment by paulzakin** [comment]
Thanks for the report! 

Both I just fixed in v2.8.0 :)
