### ISSUE TITLE
Can't see protein 

### ISSUE THREAD

**Issue by john-markowsky** [successible/cleanslate#76]
After the 💪 there's no amount for my protein on each food item in the diary.

**Comment by john-markowsky** [comment]
![Screenshot_20240218-115658](https://github.com/successible/cleanslate/assets/123923257/4ce3cf4d-d115-4ef6-a27e-2af3f8bce20c)
 Here's a screenshot.

Thanks for making this app free btw !✌️

**Comment by paulzakin** [comment]
Hmmmm....

Can you switch off enablePlanning in settings and see if that resolves it?

**Comment by paulzakin** [comment]
Ok, I can replicate that! Just deployed the fix. Thanks for the report! Feel free to reopen if it occurs again.

**Comment by john-markowsky** [comment]
It fixed it, thank you!
