### ISSUE TITLE
Unit variety

### ISSUE THREAD

**Issue by sgomez92** [successible/cleanslate#86]
Hi! First of all, I'd like to say I've just started using you app and I really like it.
I wanted to suggest adding some other Units of Measurement to the app, mostly on the metric system.
Using Km for excercise tracking, cm for height measuring, kg for weight measuring, etc.
It should be simple enough to add code that does the conversions on the backend and it would save some hassle for people who don't use the imperial system (having to do conversions on another app or site is kind of annoying and it goes against the quick and easy usage of your app).
Thanks a bunch!

**Comment by paulzakin** [comment]
That is a very good idea. You can clearly see my American bias working in :)

However, because it’s a mostly American audience, I think what I’ll do is have it be set when you first login for the first time and then you can change it in settings page. Does that sound reasonable you?

And fun fact, a lot of the internals are ready and are metric!

But just so I’m not missing anything, can you list the units that you would like to see?

**Comment by sgomez92** [comment]
That sounds good.
As far as I can see on the app, most of the excercise tracking is based on weight and distance, so here you can set the option for kg instead of lbs and km instead of miles.
The same measure of kg instead of lbs and cm instead of feet and inches can go into the config tab to set the user's personal data (weight and height).
The units for food (i.e kcal, grams) are fine because I think it's kind of universal? I use the American system where I'm from (South America) so that's no issue for me, and the customizable foods/recipes already uses grams for servings so it's cool.
I guess mostly that: for distance add km, for weight kg, for height cm (this might need a little bit of UI tweaking because you have to input tabs for feet/inch..sorry).
Thanks in advance!

**Comment by paulzakin** [comment]
Ok great - I’ll let you know when I finish - and you can give feedback on thread

**Comment by paulzakin** [comment]
Done! Let me know what you think :)

**Comment by sgomez92** [comment]
Seems to be working fine! Great job!
