### ISSUE TITLE
Serving size measurements for custom recipes and total weight for recipes.

### ISSUE THREAD

**Issue by sgomez92** [successible/cleanslate#89]
Custom foods allows you to set a custom serving type but also gives you weighs in grams, oz or other measures like TBSP.
Custom recipes doesn't and it would be super useful.
For example, today I created a custom recipe for a vegetable, rice and chicken wok. I set each individual ingredients and the weights I used. At the end it only let me set the "serving" as the full recipe, which was over a kg of food. This made me had to input in my diary about 0.4 of that which was the 400 grams I ate. I lucked out on the calculation because the total amount of food was about kilo, but if the total amount was something else the calculation would have been more complicated.
This could easily be solved by having the app record the total weight of a recipe and giving you an option to set the amount of grams you ate of that recipe instead of having only the custom serving size. Calculating the protein and carbs amount automatically from summing the ingredients and dividing by total weight.

Hope I was clear enough. I cook without using set recipes and being able to record the ingredients separately and see how much calories a serving of what I made without resorting to extra calulations would go a really long way for me.
I know the custom recipe is maybe made for people who just input what a recipe tells them, but using it as a tool for a person to just cook something and check the calories of a custom serving in grams could also be great.

Thanks a bunch in advance!

**Comment by paulzakin** [comment]
This is an interesting idea. I’ll chat with my partner about it.

**Comment by paulzakin** [comment]
So - to clarify - let's us say you create a recipe for three ingredients: A, B, C  - you want to be able to enter the "per" measurements just like custom foods?

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/19244099/233885039-a3177633-44be-43a9-8e17-91b0dd34ee9e.png">

**Comment by paulzakin** [comment]
Or did you have a different system in mind?

**Comment by sgomez92** [comment]
That wasn't what I had in mind but that can also be useful if you're adding a recipe from a book for example. Recipes usually serve 2 or more people so that's a nice added bonus if you already know beforehand the serving sizes and weights.

What I had in mind is that once you add the recipe you aren't restricted to a single serving type which you customly created. Instead, have the app sum the weights of the ingredients and then let you decide how much grams of that recipe you ate so that it gives you the correct calorie and protein calculations for that amount of grams.

For example, the "wok de poio" that I created only lets me input this:
![image](https://user-images.githubusercontent.com/131557313/233887087-85e75d0c-4804-4e96-a5fd-f23dc2b0acad.png)
The recipe creator lets me put into "label" what will later be the serving type (That roughly translates to whole wok in my example). But after that it doesn't let me choose anything else but that label, so I have to input a decimal aproximation if that label isn't exactly one serving (which is also complicated if the serving varies depending on how much you ate).

Instead it would be cool for it to let me input the amount of grams I ate when I choose the recipe from the finder, like when setting a custom food:
![image](https://user-images.githubusercontent.com/131557313/233888610-fc7be4db-5b7c-4da9-96d3-f6234174da9c.png)

This way I wouldn't have to worry about knowing beforehand the recipe's serving size and just let the app figure it out by calculating it from the weights or amounts which I input inside the recipe:
![image](https://user-images.githubusercontent.com/131557313/233887850-c46000de-df4b-46db-aa80-1284134a4196.png)

From what I've seen the app already knows an estimate of weights for when you're using a different measure than grams (when you set for example 1 egg and then switch to grams it goes to 50 automatically, is this a feature or bug? haha). So mixing grams with tbsp or amounts wouldn't be that much of a problem (maybe?).

**Comment by paulzakin** [comment]
Got it - hmmmm not all foods have grams (custom foods can skip them) but if all foods do it could work - but what about cooking? You have ingredients A and B that each are 500 gram. After combing and cooking them, the final product is 800g. You measure out a portion to eat (200g). Clean Slate will assume you eat 200/1000 rather than 200/800 so it will get the calories wrong. That is why I feel it makes more sense to weigh the final product and add it as an option much like custom foods. But what do you think?

**Comment by sgomez-cornelis** [comment]
This is the thing with measuring weights and calories in raw vs. cooked foods. You won't know how much weight was lost/gained unless you weigh your food before and after cooking. This stays easy if you cook for one, but that's never my case as I usually cook for two (my wife and I) or sometimes for four so we have spare food for another day.

The way I see this working would be:
1) You create a recipe based on raw ingredients and add their inividual weights and calories. The app shows you the total weight as you add raw ingredients.
2) You cook that recipe and then weigh the cooked result. The app has an input "Cooked weight".
3) The app has now the raw vs cooked weights and can scale the calories and protein (we assume they stayed roughly the same, as it usually happens..maybe not with protein but we can assume calories were not lost/gained and you input raw oil if you used it for cooking).
4) You save the recipe and when you input your daily you just put x grams of that recipe and the app would give you the right amount of calories (with the proper ratio when cooked).
The only thing I see here is that you should have an option to tick "cooked" when adding your serving to the daily, so the app knows which weight/calorie ratio to use. I don't see who would weigh raw food for portioning though, but I guess it can't hurt to have options?

How does that sound?

I don't know how the system works right now, but when you save your recipe now it's still using the weights you input, regardless of the status of the ingredients (you can add raw or cooked and mix both into the recipe). Other than that it makes no sense to portion your food before cooking it as you don't know the weight of your end product.
 
I hope this isn't too disruptive, but I think it would make the countings a bit more accurate.

Cheers!

**Comment by sgomez-cornelis** [comment]
Maybe I overcomplicated my explanation. The only thing that comes to mind is just adding a "cooked weight" section for the custom recipes. Once the recipe is done you add the cooked weight of the total recipe, and then when you set the weight for daily consumption the app uses the cooked weight if it exists or the raw weight if it doesn't.
You can even add a flag for "cooked" to not have to check for it and let the user add that.

I believe this would improve the precision when counting calories on custom and variying recipes and make the users life a bit easier because, as we previously discussed, there's a scaling difference when counting calories on cooked vs uncooked food that the custom recipe feature isn't covering.

I understand that it could be complicated to implement or too much to ask. Just my two cents from personal experience as a person who cooks most of the time meals with multiple servings.

Cheers!

**Comment by paulzakin** [comment]
Got it got it, I think we’re on the same page here. We allow the user to set the final weight of the recipe as one numerical input and that’s it. I am thinking about it in terms of grams per serving and you were thinking about it in terms of the total weight but it’s kind of the same thing so I think this is a good idea and we will add it. I think the total cooked weight of the recipe makes sense as the way to add this information but I’ll talk with my partner.

**Comment by paulzakin** [comment]
Deployed! 

This one was tricky, so I'll be curious what you think. I think it does what you want and makes sense to other people. You can now set the grams (weight unit) and volume unit (like cups) associated with a recipe under the "edit units" button. Let me know what you think!
