### ISSUE TITLE
Clicking on a custom recipe from custom recipes list works as "add recipe" button

### ISSUE THREAD

**Issue by sgomez92** [successible/cleanslate#90]
![bug](https://user-images.githubusercontent.com/131557313/233882892-bd46060b-b87b-4502-9128-96e691fba446.png)

When clicking the name of a custom recipe on the custom recipe list, it goes to the "add recipe" window and it's pretty confusing.
You may want to remove the hyperlink there or just have it go to the "edit" window for that recipe (same as clicking the pencil button).

**Comment by paulzakin** [comment]
Yeah, that’s a good idea. I’ll remove the hyperlink
