### ISSUE TITLE
Calorie count when "calorie/protein count up" is enabled

### ISSUE THREAD

**Issue by sgomez92** [successible/cleanslate#97]
Hi, I wanted to ask if it was possible to have the app take into account excercise for the total calorie count when the option for "count up" is enabled.
I noticed when this option is disabled and you add excercise calories it subtracts from the total remaining for the day, but when the option is enabled the value stays at only calories consumed.
A simple solution would be to subtract from the current spent or to simply increase the total amount, i.e:

Calories 800/1800

If I add excercise of say, 400 kcal: it should show Calories 400/1800 or Calories 800/2200

Cheers!

**Comment by paulzakin** [comment]
Let me look at this, but it seems reasonable!

**Comment by paulzakin** [comment]
Deployed - let me know what you think!

**Comment by sgomez92** [comment]
Works perfectly! Adding to total count instead of subtracting from current was the best choice to avoid confusion.
Thanks a bunch!
