### ISSUE TITLE
unknown shorthand flag: 'f' in -f error when building/deploying

### ISSUE THREAD

**Issue by mikesellt** [successible/cleanslate#97]
Hello, 

First of all, I'm really happy to try out self-hosting Cleanslate.  I am having an issue during deployment on a Synology NAS (latest version - 7.2).  Here's the output when I try and run the build script:

        Tim@BigRed:/volume1/docker/cleanslate$ sudo git pull origin main; bash deploy.sh
        Password:
        From https://github.com/successible/cleanslate
         * branch            main       -> FETCH_HEAD
        Already up to date.
        From https://github.com/successible/cleanslate
         * branch            main       -> FETCH_HEAD
        Already up to date.
        Deploying with file: docker-compose.yml
        unknown shorthand flag: 'f' in -f
        See 'docker --help'.
        
        Usage:  docker [OPTIONS] COMMAND

I have tried googling this, and it seems the Docker compose version may be the issue on my end, but I can't update the compose version and I'm not sure how to get the "up" command to fire with or without the -f.  

Have you seen this issue before with other deployments?  I can try and deploy with a different machine or VM, but ideally I'd run it on the hardware I'm attempting.  

Thanks

**Comment by paulzakin** [comment]
Hmmmmmm.... Let's try to figure this out.

Can you post the output of `docker compose version` and `docker --version`

And nope, this a new report for me :(

**Comment by mikesellt** [comment]
Thanks for the quick reply!  And yes, I should've probably opened this as "question" instead of "bug."  thanks for changing that.  

"docker compose version" didn't work for me.  I had to run it as: 

docker-compose version
Docker Compose version v2.9.0-6413-g38f6acd

docker --version
Docker version 20.10.23, build 876964a

**Comment by mikesellt** [comment]
Since the "docker compose version" command didn't work, but the "docker-compose version" DID work, should I just edit the deploy.sh file to use "docker-compose" instead of "docker compose"?

**Comment by paulzakin** [comment]
Let's give that a shot?

[Looks like you have the older version of Docker Compose](https://stackoverflow.com/questions/66514436/difference-between-docker-compose-and-docker-compose), that's why there is a difference

**Comment by mikesellt** [comment]
Sorry for the late reply.  I did try the change, and it gets much further now, but now I'm having the following errors: 

Tim@BigRed:/volume1/docker/cleanslate$ sudo git pull origin main; bash deploy.sh
Password:
From https://github.com/successible/cleanslate
 * branch            main       -> FETCH_HEAD
Already up to date.
From https://github.com/successible/cleanslate
 * branch            main       -> FETCH_HEAD
Already up to date.
Deploying with file: docker-compose.yml
[+] Building 0.0s (0/0)
[+] Building 0.0s (0/0)
no valid drivers found: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dcleanslate%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dcleanslate%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied


I've tried running via regular user as well as sudo with the same result.

**Comment by paulzakin** [comment]
So - this unfortunately is not a problem with clean slate,  it is still a problem with your underlying docker installation and your permissions :(

**Comment by paulzakin** [comment]
I think these links cover how to fix the problem from my read of them.

https://www.digitalocean.com/community/questions/how-to-fix-docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket

https://stackoverflow.com/questions/47854463/docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socke

**Comment by mikesellt** [comment]
Yes I was afraid of that.  I think the issue is probably how Synology runs Docker on the backend and integrates it with everything else, but I'll check those links you provided.  I think I'll try spinning this up on a separate host or in a VM and that should clear up these issues, I think.  Thanks a lot for taking the time to help out!

**Comment by paulzakin** [comment]
Sure, best of luck to you!
